export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default ({ children }: { children: React.ReactNode }) => (
    <html lang="en">
        <body>{children}</body>
    </html>
);
